services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bank-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=bank
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  db-data:
